quanlyfood/quanlyfood/Controllers/Admin/OrderAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using quanlyfood.Repository;
using quanlyfood.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace quanlyfood.Controllers.Admin
{
    [RoutePrefix("admin")]
    public class OrderAdminController : BaseAdminController
    {
        CartRepository order_repository = new CartRepository();
            
        [Route("order/list")]
        // GET: OrderAdmin
        public ActionResult Index(int? page)
        {
            int page_number = (page ?? 1);
            int page_size = 10;

            List<OrderModel> list_orders = order_repository.getListOrder();
            ViewBag.list_orders = list_orders.ToPagedList(page_number, 20);
            return View();
        }

        // GET: BanhAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Route("order/edit/{id:int}")]
        // GET: OrderAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            OrderModel order = order_repository.getOrderById(id);
            
            if (order == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.order = order;
            return View(order);
        }

        
    }
}

quanlyfood/quanlyfood/Views/OrderAdmin/Edit.cshtml
@model quanlyfood.Models.OrderModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cập nhật đơn hàng</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Edit", "Order", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Đơn hàng</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.MaDonHang)
                                    <div class="row-fluid">
                                        <!--Edit Main Content Area here-->
                                        <div class="span12" id="divMain">
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>#</th>
                                                        <th>Tên Bánh</th>
                                                        <th>Số Lượng</th>
                                                        <th>Đơn Giá</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @foreach (var item in ViewBag.order.orderDetail)
                                                    {
                                                        <tr>
                                                            <td>1</td>
                                                            <td>@item.TenBanh</td>
                                                            <td>@item.Soluong</td>
                                                            <td>@String.Format("{0:0,0}", @item.DonGia)</td>
                                                        </tr>
                                                    }
                                                    <tr>
                                                        
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <!--End Main Content Area-->
                                    </div>
                                    <!--<div class="form-group">
                                        @Html.LabelFor(model => model.TinhTrangGiaoHang, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.TinhTrangGiaoHang, new { htmlAttributes = new { @class = "" } })
                                            @Html.ValidationMessageFor(model => model.TinhTrangGiaoHang, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Save" class="btn btn-default" />
                                        </div>
                                    </div>-->
                                </div>
                            }
                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

quanlyfood/quanlyfood/Views/OrderAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Danh sách đơn hàng</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Mã Đơn Hàng</th>
                                    <th>Tình Trạng Giao Hàng</th>
                                    <th>Ngày Đặt</th>
                                    <th>Ngày Giao</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int index = 1;}
                                @foreach (var item in ViewBag.list_orders)
                                {
                                    <tr>
                                        <td>@index</td>
                                        <td><a href="/admin/order/edit/@item.MaDonHang">@item.MaDonHang</a></td>
                                        <td>
                                            @if(@item.TinhTrangGiaoHang == false)
                                            {
                                                @Html.Raw("Chưa Giao Hàng");
                                            }
                                            else
                                            {
                                                @Html.Raw("Đã Giao Hàng");
                                            }
                                        </td>
                                        <td>@String.Format("{0:MM/dd/yyyy}", @item.NgayDat)</td>
                                        <td>
                                            @String.Format("{0:MM/dd/yyyy}", @item.NgayGiao)
                                        </td>
                                    </tr>
                                    index++;
                                }
                                
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                
                                @for (var i = 1; i <= ViewBag.list_orders.PageCount; i++)
                                {
                                    <li><a href="@Url.Action("Index", "OrderAdmin", new { page = @i })">@i</a></li>
                                }
                                
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>