quanlyfood/quanlyfood/Controllers/Admin/ProductAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using quanlyfood.Repository;
using quanlyfood.Models;
using PagedList;
using PagedList.Mvc;
using System.IO;


namespace quanlyfood.Controllers.Admin
{
    [RoutePrefix("admin")]
    public class ProductAdminController : BaseAdminController
    {
        BanhRepository product_repository = new BanhRepository();

        [Route("product/list")]
        // GET: BanhAdmin
        public ActionResult Index(int? page)
        {
            int page_number = (page ?? 1);
            int page_size = 10;

            List<BanhModel> list_products = product_repository.getListProduct("all");
            ViewBag.list_products = list_products.ToPagedList(page_number, 20);
            return View();
        }

        // GET: BanhAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [Route("product/add")]
        // GET: BanhAdmin/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(data.LOAIs.ToList(), "MaLoai", "TenLoai");
            return View();
        }

        [Route("product/add")]
        // POST: BanhAdmin/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(BANH product, FormCollection collection, HttpPostedFileBase anhbia)
        {
            var anh_bia = Path.GetFileName(anhbia.FileName);
            var path = Path.Combine(Server.MapPath("~/uploads"), anh_bia);
            ViewBag.MaLoai = new SelectList(data.LOAIs.ToList(), "MaLoai", "TenLoai");
            if(anhbia == null)
            {
                ViewBag.thong_bao = "Vui lòng chọn ảnh bìa";
                return View();
            }
            else
            {
                if (ModelState.IsValid)
                {
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.thong_bao = "Hình ảnh đã tồn tại";
                        return View();
                    }
                    else
                    {
                        anhbia.SaveAs(path);
                    }
                    
                }
                
            }

            try
            {
                product.AnhBia = "/uploads/"+anh_bia;
                data.BANHs.InsertOnSubmit(product);
                data.SubmitChanges();
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }

        [Route("product/edit/{id:int}")]
        // GET: BanhAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            BANH product = data.BANHs.SingleOrDefault(n => n.MaMon == id);
            ViewBag.MaLoai = new SelectList(data.LOAIs.ToList(), "MaLoai", "TenLoai", product.MaLoai);
            if (product == null)
            {
                return RedirectToAction("Index");
            }
            return View(product);
        }

        [Route("product/edit/{id:int}")]
        // POST: BanhAdmin/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(int id, FormCollection collection, HttpPostedFileBase anhbia)
        {
            
            var product = data.BANHs.SingleOrDefault(n => n.MaMon == id);
            ViewBag.MaLoai = new SelectList(data.LOAIs.ToList(), "MaLoai", "TenLoai", product.MaLoai);
            
                if(anhbia != null)
                {
                    var anh_bia = Path.GetFileName(anhbia.FileName);
                    var path = Path.Combine(Server.MapPath("~/uploads"), anh_bia);
                    if (System.IO.File.Exists(path))
                    {
                        ViewBag.thong_bao = "Hình ảnh đã tồn tại";
                        return View(product);
                    } else{
                        anhbia.SaveAs(path);
                        product.AnhBia = "/uploads/" + anh_bia;
                    }


                }

                product.TenMon = collection["TenMon"];
                product.GiaBan = decimal.Parse(collection["GiaBan"].ToString());
                product.MoTaNgan = collection["MoTaNgan"];
                product.MoTa = collection["MoTa"];
                product.MaLoai = int.Parse(collection["MaLoai"]);
                product.TrangThai = byte.Parse(collection["TrangThai"].ToString());
                data.SubmitChanges();
                return RedirectToAction("Index");
            
        }

        [Route("product/delete/{id:int}")]
        public ActionResult Delete(int id)
        {
            var product = data.BANHs.SingleOrDefault(n => n.MaMon == id);
            try
            {
                product.TrangThai = 0;
                data.SubmitChanges();
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

quanlyfood/quanlyfood/Views/ProductAdmin/Create.cshtml
@model quanlyfood.Models.BANH

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Thêm mới sản phẩm</h1>
        </div>
    </div>
    <div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <!-- /.panel-heading -->
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                    @using (Html.BeginForm("Create", "ProductAdmin", FormMethod.Post, new { @enctype ="multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.TenMon, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <textarea name="MoTaNgan"></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <textarea name="MoTa"></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                   <input type="file" name="anhbia" />
                                    @*thong bao trung*@
                                    @ViewBag.thong_bao
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Ngaycapnhat, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="date" name="Ngaycapnhat" class="form-control"/>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MaLoai, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("MaLoai", null, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Tạo" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                    </div>                     
                </div>
            </div>
        </div>
    </div>
</div>

</div>

    

    <div>
        @Html.ActionLink("Về danh sách", "Index")
    </div>

quanlyfood/quanlyfood/Views/ProductAdmin/Edit.cshtml
@model quanlyfood.Models.BANH

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Cập nhật sản phẩm</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Edit", "ProductAdmin", FormMethod.Post, new { @enctype = "multipart/form-data" }))
                            {
                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">
                                    <h4>Bánh</h4>
                                    <hr />
                                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                    @Html.HiddenFor(model => model.MaMon)

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TenMon, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.TenMon, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.TenMon, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.MoTaNgan, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <textarea name="MoTaNgan">@Model.MoTaNgan</textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <textarea name="MoTa">@Model.MoTa</textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.AnhBia, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            <input type="file" name="anhbia" />
                                            @*thong bao trung*@
                                            @ViewBag.thong_bao
                                            <img src="@Url.Content(@Model.AnhBia)" width="80px"/>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.MaLoai, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.DropDownList("MaLoai", null, new { @class = "form-control" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
                                        <div class="col-md-10">
                                            @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-offset-2 col-md-10">
                                            <input type="submit" value="Save" class="btn btn-default" />
                                        </div>
                                    </div>
                                </div>
                            }
                            <div>
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    

    

quanlyfood/quanlyfood/Views/ProductAdmin/Index.cshtml
@using PagedList.Mvc;
@model PagedList.PagedList < quanlyfood.Models.BANH>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Danh sách sản phẩm</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Tên Bánh</th>
                                    <th>Giá Bán</th>
                                    <th>Ảnh Bìa</th>
                                    <th>Ngày cập nhật</th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int index = 1;}
                                @foreach (var item in ViewBag.list_products)
                                {
                                    <tr>
                                        <td>@index</td>
                                        <td><a href="/admin/product/edit/@item.MaMon">@item.TenMon</a></td>
                                        <td>@String.Format("{0:0,0}", @item.GiaBan)</td>
                                        <td><img src="@item.AnhBia" style="width:80px ; height:80px"/></td>
                                        <td>
                                            @if(@item.Ngaycapnhat != null)
                                            {
                                                   @String.Format("{0:MM/dd/yyyy}", @item.Ngaycapnhat)
                                            }
                                        </td>
                                        <td>
                                            <a href="/admin/product/delete/@item.MaMon" class="btn btn-danger btn-xs" onClick='return showConfirmDelete("Bạn có muốn xóa @item.TenMon ?")'><i class="fa fa-trash" aria-hidden="true"></i></a>
                                        </td>
                                    </tr>
                                    index++;
                                }
                                
                            </tbody>
                        </table>
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                
                                @for (var i = 1; i <= ViewBag.list_products.PageCount; i++)
                                {
                                    <li><a href="@Url.Action("Index", "ProductAdmin", new { page = @i })">@i</a></li>
                                }
                                
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>